"""added owners

Revision ID: 11212b030eba
Revises: 548ba3e94818
Create Date: 2022-03-02 15:44:55.004168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11212b030eba'
down_revision = '548ba3e94818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###
